// Generated by CoffeeScript 1.6.3
(function() {
  var client;

  client = angular.module('client', []);

  client.controller('MainCtrl', function($scope, $http) {
    $scope.palettes = {};
    $scope.user = {};
    $scope.toggle = 1;
    $scope.user.name = "xqweasdx";
    $scope.user.apiKey = "76381a8f3b714a02be3b944a21f435d4";
    $scope.getAccount = function(user) {
      var _this = this;
      $scope.toggle = 0;
      $http.post('/getAccount', user).success(function(resp) {
        $scope.palettes = resp;
        return console.log(resp);
      });
      return console.log(user);
    };
    return $scope.resourceClick = function(productName, resourceName, feature, data) {
      var _this = this;
      return $http.post('/' + productName + '/' + resourceName + '/' + feature, data).success(function(resp) {
        $scope.palettes[productName].models = resp;
        return console.log(resp);
      });
    };
  });

}).call(this);
